### PR TITLE
Fixing inconsistencies with the table and other parts of the document

### PR DESCRIPTION
**Pull request by Anirban166**
Stuff like capitalization, grammar, and the paragraph describing `atime` (the para above needs revising too - I'm not sure what you were trying to convey from what you wrote, or if it highlights anything particularly significant as 'missing')

### CODE REVIEW

**Comment by Anirban166** [comment]
There are still a lot of other issues in your writing that need to be resolved - I'm correcting some of them, but you will need to look into things and make reasonable edits with your inputs.

In the 'Comparative Benchmarking' section for example, these sentences are repeated for every case:
```
atime provides asymptotic timing measurements for more accurate analysis.
atime is designed for R code, whereas xyz is specific to Python.
atime offers more detailed insights into performance differences than xyz.
By providing higher resolution measurements, atime is a more advanced tool for performance analysis.
```
Why is it like that? (And by 'xyz' I'm referring to literally every software/function in discussion - `time.it`, `profile.run`, `airspeed velocity`, 'pytest-benchmark`, `conbench`, and `touchstone`)

It shouldn't feel like copy-paste when reading, and neither should you repeat yourself. I would advise you to try to find different points for each case here, and then rephrase every statement you write that is similar to something you wrote previously.

**Comment by Anirban166** [comment]
There are still a lot of other issues in your writing that need to be resolved - I'm correcting some of them, but you will need to look into things and make reasonable edits with your inputs.

In the 'Comparative Benchmarking' section for example, these sentences are repeated for every case:
```
atime provides asymptotic timing measurements for more accurate analysis.
atime is designed for R code, whereas xyz is specific to Python.
atime offers more detailed insights into performance differences than xyz.
By providing higher resolution measurements, atime is a more advanced tool for performance analysis.
```
Why is it like that? (And by 'xyz' I'm referring to literally every software/function in discussion - `time.it`, `profile.run`, `airspeed velocity`, `pytest-benchmark`, `conbench`, and `touchstone`)

It shouldn't feel like copy-paste when reading, and neither should you repeat yourself. I would advise you to try to find different points for each case here, and then rephrase every statement you write that is similar to something you wrote previously.

**Comment by Anirban166** [comment]
Some feedback from what I'm seeing:

- Re-read what you wrote till you're sure that it makes sense both grammatically and in what you are trying to state/convey
- Use punctuation appropriately and where necessary (commas for example)
- If you are using `xyz()` then you do not need to state that `xyz` is a function, given the use of parentheses

For example, if you were to keep in mind these three points above and make changes for what you wrote here:
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L139
This is what I would expect:
```
\noindent As mentioned above, the core functions of the \texttt{atime} package, \code{atime()} and \code{atime\_versions()}, ...
```
- Always use the correct capitalizations for software (such as `GitHub` instead of `github`, or as Toby mentioned, `touchstone` instead of `Touchstone` - I cross-checked and had to correct multiple names of software/functions that were included in the comparative benchmarking section for e.g.), and keep it consistent as sometimes you write it correctly but later on in the document I find a different version (like `airspeed velocity` in the table, and then `Airspeed Velocity` below in writing. Also, ensure names by themselves are correct - for e.g., `pytest-benchmark` and not `pytest-benchmarks`)
- Highlighting names of software/packages/functions should be consistent as well. Some places I'll see a `\texttt{ ... }` wrapper correctly, while others I'll not

**Comment by Anirban166** [comment]
More points to consider:

- Instead of using the name of a noun (such as `atime` and `data.table` in your writing) repeatedly (especially multiple times within a paragraph or statement even), you should use a pronoun (such as "it") to refer going forward. (This helps make sentences less repetitive and more fluid)

> - Highlighting names of software/packages/functions should be consistent as well. Some places I'll see a \texttt{ ... } wrapper correctly, while others I'll not
- I'll be taking care of this (highlighting) within this PR, but another element you need to maintain consistency in is indentation - Please keep it in mind, and also avoid cases like this:
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L143

> - If you are using xyz() then you do not need to state that xyz is a function, given the use of parentheses
- Adding to what I said here: Use `()` only when it's a function and not referring to a package.
For example, `atime()` here should be `atime`:
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L483

> - It shouldn't feel like copy-paste when reading, and neither should you repeat yourself.
- Another, rather subtle example for this would be parts such as 
' ... providing a comprehensive understanding of the impact of the regression and the effectiveness of the new version.' (at the end of [this line](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L371C1037-L371C1150)), 
' ... helps in understanding the impact of the regression and the effectiveness of the fix.', and 
' ... highlighting the impact of the regression and the effectiveness of the fix.' (in the very [next example](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L395))
(The phrases 'impact of the regression' and 'effectiveness of the fix' are being used too repetitively)

> - Re-read what you wrote till you're sure that it makes sense both grammatically and in what you are trying to state/convey
- Emphasizing on this again since the grammatical flow and sentence structure is off in a lot of areas. If needed, use a tool to help you out with it. (I haven't tried it, but maybe something like Grammarly?)

Also, I see that what I mentioned to correct [here](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/pull/2#issuecomment-2311656067) has not been completed (I checked both here and on Overleaf) yet, so please make those changes as well.

For instance, these two parts:
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L151

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L394

**Comment by Anirban166** [comment]
Hello Doris, you can proceed to merge this PR.

As Toby told me to, I tried to provide some detailed feedback above apart from edits but feel free to let me know if you need more suggestions/help and I'd be open to review your changes over the weekend.

One last nitpick till then: 
https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/3b09efc549ef3900d27bccf86cca6f0888e256ff/DorisAmoakohene.tex#L185

I'd instead say something like:
```
atime allows for comparative benchmarking, thereby helping to evaluate the relative performance efficiency of an R package amongst other packages. By conducting such benchmarks, we can gain valuable insights that can help a package to remain robust.
```

**Comment by Anirban166** [comment]
I'd suggest you to first incorporate the changes from here into your LaTeX file (since right now this will be a conflict to resolve before merging on GitHub with your latest update that still does not have a lot of the changes we discussed)

Please read what I said here and try to make changes accordingly.

**Comment by Anirban166** [comment]
I'd suggest you to first incorporate the changes from here into your LaTeX file (since right now this will be a conflict to resolve before merging on GitHub with your latest update that still does not have a lot of the changes we discussed)

Please read what I said here and try to make the changes accordingly!

**Comment by Anirban166** [comment]
Also, @tdhock do you have any recommendations? I think it would be valuable to have your feedback here too so Doris can look at one place and move ahead with the modifications.

**Comment by Anirban166** [comment]
Also, @tdhock do you have any recommendations on this? I think it would be valuable to have your previous feedback here too so Doris can look at one place and move ahead with the modifications.

**Comment by DorisAmoakohene** [comment]
Hi @Anirban166 kindly check file instead https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/main/DorisAmoakohene.tex, I dont know what file you are looking at but my update are here.

**Comment by Anirban166** [comment]
It is the same file I'm looking at..have you crossed-check the diffs I made here (click on the 'Files changed' tab or [check here](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/pull/4/files)) with the state of the current [.tex file](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/main/DorisAmoakohene.tex)? (it's the same one that you shared the link to above)

**Pull request merged**
