### PR TITLE
Some corrections

### PR DESCRIPTION
**Pull request by Anirban166**

### CODE REVIEW

**Comment by Anirban166** [comment]
This PR is just another pass of corrections for what I noticed. 

There are quite a few statements/parts which you need to edit - for e.g. in the 'Proposed method: atime for measuring asymptotic time and memory' section, these are some lines which are grammatically wrong / not making full sense / half-done:

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/a0f19843db200f45fcca212fada717c2a2d24332/DorisAmoakohene.tex#L167

(I included an edit to this line in my recent commit for the last statement, but mentioning it in case you wanted to convey it differently)

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/a0f19843db200f45fcca212fada717c2a2d24332/DorisAmoakohene.tex#L169

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/a0f19843db200f45fcca212fada717c2a2d24332/DorisAmoakohene.tex#L181

Also other places in the document, such as this statement: ('almost as the first simple')

https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/a0f19843db200f45fcca212fada717c2a2d24332/DorisAmoakohene.tex#L447

**Comment by Anirban166** [comment]
Hello Doris, are you done with the corrections above?

Also, can you please update the `.tex` file here on GitHub? I have some more corrections (for e.g. the table contents, code highlighting, etc.) ready to include, but I'll check your edits here first to not overlap.

**Comment by Anirban166** [comment]
Hello Doris, are you done with the corrections above?

Also, can you please update the [`.tex`](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/main/DorisAmoakohene.tex) file here on GitHub with the latest changes on Overleaf? I have some more corrections (for e.g. the table contents, code highlighting, etc.) ready to include, but I'll check your edits here first to not overlap.

**Comment by Anirban166** [comment]
Hello Doris, are you done with the corrections above?

Also, can you please update the [`.tex`](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/main/DorisAmoakohene.tex) file here on GitHub with the latest changes on Overleaf? I have some more corrections (for e.g. the table contents, code highlighting, etc.) ready to be included, but I'll check your edits here first to avoid overlap.

**Comment by DorisAmoakohene** [comment]
> Hello Doris, are you done with the corrections above?
> 
> Also, can you please update the [`.tex`](https://github.com/DorisAmoakohene/Doris-Amoakohene-atime-for-asymptotic-Timings/blob/main/DorisAmoakohene.tex) file here on GitHub with the latest changes on Overleaf? I have some more corrections (for e.g. the table contents, code highlighting, etc.) ready to be included, but I'll check your edits here first to avoid overlap.

Yes I have made changes to the comment you made, I have also push the updated changes from overleaf to github

**Pull request merged**
